/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GloBot */

#ifndef _Included_GloBot
#define _Included_GloBot
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
