/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ParticleSystem */

#ifndef _Included_ParticleSystem
#define _Included_ParticleSystem
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
