/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Quake */

#ifndef _Included_Quake
#define _Included_Quake
#ifdef __cplusplus
extern "C" {
#endif
#undef Quake_BPRINT
#define Quake_BPRINT 0L
#undef Quake_SPRINT
#define Quake_SPRINT 1L
#undef Quake_CENTERPRINT
#define Quake_CENTERPRINT 2L
#undef Quake_CONPRINT
#define Quake_CONPRINT 3L
#undef Quake_DBGPRINT
#define Quake_DBGPRINT 4L
/*
 * Class:     Quake
 * Method:    bPrint
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Quake_bPrint
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Quake
 * Method:    sPrint
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_Quake_sPrint
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     Quake
 * Method:    cPrint
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_Quake_cPrint
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     Quake
 * Method:    conPrint
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Quake_conPrint
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Quake
 * Method:    condPrint
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Quake_condPrint
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Quake
 * Method:    getCVar
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_Quake_getCVar
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Quake
 * Method:    setCVar
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Quake_setCVar
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     Quake
 * Method:    glTexCoord2f
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_Quake_glTexCoord2f
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     Quake
 * Method:    glVertex3f
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_Quake_glVertex3f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     Quake
 * Method:    drawParticle
 * Signature: (FFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_Quake_drawParticle
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
